default:
  image: docker:19.03.12

stages:
  - Lint
  - Test
  - Deploy

# Lint the webpage
Lint:
  image: node:14.18.1
  stage: Lint
  script:
    - cd ./src
    - yarn install --frozen-lockfile
    - yarn lint

# Run the Test cases for the webpage 
Test:
  image: node:14.18.1
  stage: Test
  script:
    - cd ./src
    - yarn install --frozen-lockfile
    - yarn test --silent
  needs:
    - job: Lint
      optional: false

Deploy:
  image: docker:latest
  stage: Deploy
  script:
    - docker build -t website .
    - docker run -d -p 3000:80 --name my-app website:latest
  needs:
    - job: Test
      optional: false
  tags:
    - website
