version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - yarn install --frozen-lockfile

  pre_build:
    commands:
      - echo Running linting...
      - yarn lint

  build:
    commands:
      - echo Running unit tests...
      - yarn test --silent
      - echo Building the React app...
      - yarn build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'build'

cache:
  paths:
    - 'node_modules/**/*'
